#!/bin/bash 
# INSTALL - utility to install all of Ollies services

BASE=`pwd`
cd oays
cp oays_all.conf oay_service oays_simple_server oays_simple_server.py ollie_at_your_service.conf ollie_at_your_service.py /opt/ollie
cd $BASE
if [ ! -f /etc/init.d/oay_service ] 
then 
    ln -s /opt/ollie/oay_service /etc/init.d/oay_service 
fi
if [ ! -f /etc/init.d/oays_simple_server ] 
then
    ln -s /opt/ollie/oays_simple_server /etc/init.d/oays_simple_server
fi
