#!/bin/bash -x 

include /opt/ollie/conf/config

ping -c1 google.ca
if [ $? -eq 0 ] 
then
    #all is find, we can speak to the Internet.
    echo 1 > /var/run/ollie/internet
else
    #hmmm, cannot see the Internet, let's try our home server
    ping -c1 $gateway
    if [ $? -ne 0 ] 
    then
        #our network connection must be down, reload the network
        /etc/init.d/network restart
    fi
fi


#test case 1: CMD to turn on the lights
#curl  -X POST http://192.168.1.97/dev_state -d "name=SS-Door&status=3"
