#!/bin/bash 

#check to see if we are already running.  If yes, stop chknet and continue with this one.
ans=`pgrep chknet`
if [ $? -eq 0 ] 
then 
    pkill chknet
fi

cntr=0
DEFAULT_ROUTE=$(ip route show default | awk '/default/ {print $3}')

while [ 1 ]   #forever...
do
    ping -c 1 $DEFAULT_ROUTE
    if [ $? -eq 1 ]    #cause 1 == no response from ping...
    then
        #default router not responding... set counter and restart network after 10 tries.
        if [ "$cntr" == "10" ] 
        then
            #restarting network interface
            systemctl restart networking
            cntr=0
        fi
        cntr=$((cntr+1))
    fi
    sleep 5
done
