#!/bin/bash -x
#
# Function: simple bash script to push a backup copy of the ProjectOllie web application
#           to the git repository
#

cp ./backup ~/ProjectOllie/webapp/ 
cp ./ProjectOllie/robots.txt ~/ProjectOllie/webapp/ProjectOllie 
cp ./ProjectOllie/models.py ~/ProjectOllie/webapp/ProjectOllie 
cp ./ProjectOllie/tests.py ~/ProjectOllie/webapp/ProjectOllie 
cp ./ProjectOllie/favicon.ico ~/ProjectOllie/webapp/ProjectOllie 
cp ./ProjectOllie/apps.py ~/ProjectOllie/webapp/ProjectOllie 
cp ./ProjectOllie/views.py ~/ProjectOllie/webapp/ProjectOllie 
cp ./ProjectOllie/admin.py ~/ProjectOllie/webapp/ProjectOllie 
cp ./wsgi.py ~/ProjectOllie/webapp/
cp ./settings.py ~/ProjectOllie/webapp/ 
cp ./urls.py ~/ProjectOllie/webapp/ 
cp ./favicon.ico ~/ProjectOllie/webapp/ 
cp ./db.sqlite3 ~/ProjectOllie/webapp/ 
cp ./templates/ollie.html ~/ProjectOllie/webapp/templates/ 
cp ./favicon.jpg ~/ProjectOllie/webapp/ 
cp ./banner.jpg ~/ProjectOllie/webapp/ 
cp ./apache/apache_django_wsgi.conf ~/ProjectOllie/webapp/apache/ 
cp ./manage.py ~/ProjectOllie/webapp/ 
